openapi: "3.0.0"
info:
  title: Simple API overview
  version: 2.0.0
paths:
  /user/{userId}:
    get:
      parameters:
        - name: userId
          in: path
          required: true
          description: Unique id of user
          schema:
            type : integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        '400':
          description: Bad request
        '403':
          description: Unauthorized
  /user:  
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        '400':
          description: Bad request
        '403':
          description: Unauthorized
components:
  schemas:
    User:
      type: object
      required:
        - username
        - email
      properties:
        username:
          type: string
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string