export const ACCOUNT = "ACCOUNT";

export const REGION = "REGION";

export const INSTANCE_ID = "INSTANCE_ID";

export const ECS_CLUSTER_ARN = "ECS_CLUSTER_ARN";
export const ECS_GROUP = "ECS_GROUP";
export const ECS_SECURITY_GROUP_ARN = "ECS_SECURITY_GROUP_ARN";
export const ECS_SUBNET_ARN = "ECS_SUBNET_ARN";
export const ECS_TASK_ROLE_ARN = "ECS_TASK_ROLE_ARN";
export const ECS_EXECUTION_ROLE_ARN = "ECS_EXECUTION_ROLE_ARN";
export const WORKER_TASK_DEF_ARN = "WORKER_TASK_DEF_ARN";
export const ORCHESTRATOR_SERVICE_NAME = "ORCHESTRATOR_SERVICE_NAME";
export const WORKER_IMAGE_NAME = "WORKER_IMAGE_NAME";
export const PROCESS_ID = "PROCESS_ID";

export const BATCH_PARALLELISM = "BATCH_PARALLELISM";

export const JOB_QUEUE_URL = "JOB_QUEUE_URL";

export const JOB_STATUS_QUEUE_URL = "JOB_STATUS_QUEUE_URL";
